lobby:
  x: 0.5
  y: 170
  z: 0.5

spawns:
  - {x: -23, y: 81, z: 35}
  - {x: -30, y: 81, z: 22}
  - {x: -35, y: 81, z: -23}
  - {x: -23, y: 81, z: -30}
  - {x: 23,  y: 81, z: -35}
  - {x: 30,  y: 81, z: -23}
  - {x: 35,  y: 81, z: 23}
  - {x: 23,  y: 81, z: 30}